/*
 * Main.java
 *
 * Created on 21. September 2006, 09:13
 */

package at.gv.wien.PortableSigner;


/**
 *
 * @author  pfp@adv.magwien.gv.at
 */
public class Main extends javax.swing.JFrame {
    
    private static SignCommandLine mycommand;
    public String copyright = "Peter Pfläging <pfp@adv.magwien.gv.at>)";
    private Preferences  prefs;
    private Version version = new Version();
    public static String result;
    
    /** Creates new form Main */
    public Main() {
        prefs = new Preferences();
        
//        System.out.println(prefs.lastInputFile + prefs.lastOutputFile + prefs.lastP12File);
        
        initComponents();
        if (mycommand.signature == null) {
            jTextFieldSignaturefile.setText(prefs.lastP12File);
        } else {
            jTextFieldSignaturefile.setText(mycommand.signature);
        }
        if (mycommand.input == null) {
            jTextFieldInputfile.setText(prefs.lastInputFile);
        } else {
            jTextFieldInputfile.setText(mycommand.input);
        }
        if (mycommand.output == null) {
            jTextFieldOutputfile.setText(prefs.lastOutputFile);
        } else {
            jTextFieldOutputfile.setText(mycommand.output);
        }
        if (mycommand.password != null) {
            jPasswordFieldPassword.setText(mycommand.password);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDialogCancel = new javax.swing.JDialog();
        jPanelCancel = new javax.swing.JPanel();
        jButtonCancelYes = new javax.swing.JButton();
        jButtonCancelNo = new javax.swing.JButton();
        jLabelCancelQuestion = new javax.swing.JLabel();
        jDialogAbout = new javax.swing.JDialog();
        jLabelAboutText = new javax.swing.JLabel();
        jButtonAboutOk = new javax.swing.JButton();
        jScrollPaneAboutVersion = new javax.swing.JScrollPane();
        jTextAreaAboutVersion = new javax.swing.JTextArea();
        jLabelAboutCopyright = new javax.swing.JLabel();
        jDialogFinished = new javax.swing.JDialog();
        jLabelFinished = new javax.swing.JLabel();
        jButtonFinishedOK = new javax.swing.JButton();
        jButtonFinishBack = new javax.swing.JButton();
        jDialogPassword = new javax.swing.JDialog();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jButtonPasswordOK = new javax.swing.JButton();
        jButtonPasswordCancel = new javax.swing.JButton();
        jLabelInput = new javax.swing.JLabel();
        jLabelOutput = new javax.swing.JLabel();
        jLabelSignature = new javax.swing.JLabel();
        jTextFieldInputfile = new javax.swing.JTextField();
        jButtonInputfile = new javax.swing.JButton();
        jTextFieldOutputfile = new javax.swing.JTextField();
        jButtonOutputfile = new javax.swing.JButton();
        jTextFieldSignaturefile = new javax.swing.JTextField();
        jButtonSignaturefile = new javax.swing.JButton();
        jButtonSignMain = new javax.swing.JButton();
        jButtonCancelMain = new javax.swing.JButton();
        jButtonAbout = new javax.swing.JButton();

        jDialogCancel.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jDialogCancel.setAlwaysOnTop(true);
        jDialogCancel.setLocationByPlatform(true);
        jDialogCancel.setModal(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("at/gv/wien/PortableSigner/i18n"); // NOI18N
        jButtonCancelYes.setText(bundle.getString("Yes")); // NOI18N
        jButtonCancelYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelYesActionPerformed(evt);
            }
        });

        jButtonCancelNo.setText(bundle.getString("No")); // NOI18N
        jButtonCancelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelNoActionPerformed(evt);
            }
        });

        jLabelCancelQuestion.setText(bundle.getString("ReallyCancel")); // NOI18N

        org.jdesktop.layout.GroupLayout jPanelCancelLayout = new org.jdesktop.layout.GroupLayout(jPanelCancel);
        jPanelCancel.setLayout(jPanelCancelLayout);
        jPanelCancelLayout.setHorizontalGroup(
            jPanelCancelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelCancelLayout.createSequentialGroup()
                .add(jPanelCancelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelCancelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButtonCancelYes)
                        .add(5, 5, 5)
                        .add(jButtonCancelNo))
                    .add(jPanelCancelLayout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(jLabelCancelQuestion)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelCancelLayout.setVerticalGroup(
            jPanelCancelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelCancelLayout.createSequentialGroup()
                .add(8, 8, 8)
                .add(jLabelCancelQuestion)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelCancelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonCancelNo)
                    .add(jButtonCancelYes)))
        );
        jDialogCancel.getContentPane().add(jPanelCancel);

        jDialogAbout.setLocationByPlatform(true);
        jDialogAbout.setResizable(false);
        jLabelAboutText.setFont(new java.awt.Font("Lucida Grande", 1, 18));
        jLabelAboutText.setText("PortableSigner");

        jButtonAboutOk.setText(bundle.getString("OK")); // NOI18N
        jButtonAboutOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutOkActionPerformed(evt);
            }
        });

        jTextAreaAboutVersion.setColumns(20);
        jTextAreaAboutVersion.setRows(5);
        jScrollPaneAboutVersion.setViewportView(jTextAreaAboutVersion);

        jLabelAboutCopyright.setText("(c) Stadt Wien");

        org.jdesktop.layout.GroupLayout jDialogAboutLayout = new org.jdesktop.layout.GroupLayout(jDialogAbout.getContentPane());
        jDialogAbout.getContentPane().setLayout(jDialogAboutLayout);
        jDialogAboutLayout.setHorizontalGroup(
            jDialogAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialogAboutLayout.createSequentialGroup()
                .add(jDialogAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jDialogAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jDialogAboutLayout.createSequentialGroup()
                            .addContainerGap()
                            .add(jScrollPaneAboutVersion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jDialogAboutLayout.createSequentialGroup()
                            .addContainerGap()
                            .add(jLabelAboutCopyright)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 241, Short.MAX_VALUE)
                            .add(jButtonAboutOk)))
                    .add(jDialogAboutLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabelAboutText)))
                .addContainerGap())
        );
        jDialogAboutLayout.setVerticalGroup(
            jDialogAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jDialogAboutLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelAboutText)
                .add(14, 14, 14)
                .add(jScrollPaneAboutVersion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jDialogAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonAboutOk)
                    .add(jLabelAboutCopyright))
                .addContainerGap())
        );
        jDialogFinished.setModal(true);
        jLabelFinished.setText("jLabel1");

        jButtonFinishedOK.setText(bundle.getString("Finish")); // NOI18N
        jButtonFinishedOK.setActionCommand(bundle.getString("Finish")); // NOI18N
        jButtonFinishedOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishedOKActionPerformed(evt);
            }
        });

        jButtonFinishBack.setText(bundle.getString("Back")); // NOI18N
        jButtonFinishBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishBackActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jDialogFinishedLayout = new org.jdesktop.layout.GroupLayout(jDialogFinished.getContentPane());
        jDialogFinished.getContentPane().setLayout(jDialogFinishedLayout);
        jDialogFinishedLayout.setHorizontalGroup(
            jDialogFinishedLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialogFinishedLayout.createSequentialGroup()
                .addContainerGap()
                .add(jDialogFinishedLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelFinished, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jDialogFinishedLayout.createSequentialGroup()
                        .add(jButtonFinishBack)
                        .add(15, 15, 15)
                        .add(jButtonFinishedOK)))
                .addContainerGap())
        );
        jDialogFinishedLayout.setVerticalGroup(
            jDialogFinishedLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jDialogFinishedLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelFinished, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jDialogFinishedLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonFinishBack)
                    .add(jButtonFinishedOK))
                .addContainerGap())
        );
        jDialogPassword.setAlwaysOnTop(true);
        jDialogPassword.setLocationByPlatform(true);
        jDialogPassword.setModal(true);
        jLabelPassword.setText(bundle.getString("PasswordLabel")); // NOI18N

        jButtonPasswordOK.setText("OK");
        jButtonPasswordOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPasswordOKActionPerformed(evt);
            }
        });

        jButtonPasswordCancel.setText("Cancel");
        jButtonPasswordCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPasswordCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jDialogPasswordLayout = new org.jdesktop.layout.GroupLayout(jDialogPassword.getContentPane());
        jDialogPassword.getContentPane().setLayout(jDialogPasswordLayout);
        jDialogPasswordLayout.setHorizontalGroup(
            jDialogPasswordLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialogPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelPassword)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPasswordFieldPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 255, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jDialogPasswordLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .add(jButtonPasswordCancel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonPasswordOK)
                .addContainerGap())
        );
        jDialogPasswordLayout.setVerticalGroup(
            jDialogPasswordLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialogPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .add(jDialogPasswordLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelPassword)
                    .add(jPasswordFieldPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jDialogPasswordLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonPasswordOK)
                    .add(jButtonPasswordCancel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        jLabelInput.setText(bundle.getString("InputLabel")); // NOI18N

        jLabelOutput.setText(bundle.getString("OutputLabel")); // NOI18N

        jLabelSignature.setText(bundle.getString("SignatureLabel")); // NOI18N

        jTextFieldInputfile.setEditable(false);

        jButtonInputfile.setText(bundle.getString("SearchButton")); // NOI18N
        jButtonInputfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInputfileActionPerformed(evt);
            }
        });

        jTextFieldOutputfile.setEditable(false);

        jButtonOutputfile.setText(bundle.getString("SearchButton")); // NOI18N
        jButtonOutputfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOutputfileActionPerformed(evt);
            }
        });

        jTextFieldSignaturefile.setEditable(false);

        jButtonSignaturefile.setText(bundle.getString("SearchButton")); // NOI18N
        jButtonSignaturefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignaturefileActionPerformed(evt);
            }
        });

        jButtonSignMain.setText(bundle.getString("SignButton")); // NOI18N
        jButtonSignMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignMainActionPerformed(evt);
            }
        });

        jButtonCancelMain.setText(bundle.getString("CancelButton")); // NOI18N
        jButtonCancelMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelMainActionPerformed(evt);
            }
        });

        jButtonAbout.setText(bundle.getString("AboutButton")); // NOI18N
        jButtonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButtonAbout)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 137, Short.MAX_VALUE)
                        .add(jButtonCancelMain)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonSignMain))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelInput)
                            .add(jLabelOutput)
                            .add(jLabelSignature))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jTextFieldOutputfile, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonOutputfile))
                            .add(layout.createSequentialGroup()
                                .add(jTextFieldInputfile, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonInputfile))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(jTextFieldSignaturefile, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonSignaturefile)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelInput)
                    .add(jTextFieldInputfile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonInputfile))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelOutput)
                    .add(jTextFieldOutputfile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonOutputfile))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelSignature)
                    .add(jTextFieldSignaturefile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonSignaturefile))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 38, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonSignMain)
                    .add(jButtonCancelMain)
                    .add(jButtonAbout))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPasswordCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPasswordCancelActionPerformed
        jDialogPassword.setVisible(false);
    }//GEN-LAST:event_jButtonPasswordCancelActionPerformed

    private void jButtonPasswordOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPasswordOKActionPerformed
        // DoSign Sign;
        jDialogPassword.setVisible(false);
        
        //TODO: Cursor
        // getParent().setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
        String inputPDFFile = "", outputPDFFile = "", signatureP12File = "";
        String password = "";
        password = String.valueOf(jPasswordFieldPassword.getPassword());
        inputPDFFile = jTextFieldInputfile.getText();
        outputPDFFile = jTextFieldOutputfile.getText();
        signatureP12File = jTextFieldSignaturefile.getText();
        if (inputPDFFile == null || outputPDFFile == null || signatureP12File == null) {
            return;
        }
        prefs.set("LastInputFile", inputPDFFile);
        prefs.set("LastOutputFile", outputPDFFile);
        prefs.set("LastP12File", signatureP12File);
        new DoSignPDF(inputPDFFile,
                outputPDFFile,
                signatureP12File,
                password);

        // getParent().setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelFinished.setText(Main.result);
        jDialogFinished.setSize(600,200);
        jDialogFinished.setVisible(true);        

    }//GEN-LAST:event_jButtonPasswordOKActionPerformed

    private void jButtonFinishBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinishBackActionPerformed
        jDialogFinished.setVisible(false);
        jLabelFinished.setText("");
    }//GEN-LAST:event_jButtonFinishBackActionPerformed
    
    private void jButtonFinishedOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinishedOKActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jButtonFinishedOKActionPerformed
    
    private void jButtonAboutOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutOkActionPerformed
        jDialogAbout.setVisible(false);
    }//GEN-LAST:event_jButtonAboutOkActionPerformed
    
    private void jButtonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutActionPerformed
        jTextAreaAboutVersion.setText(
                copyright + "\n\n" +
                version.print);
        jDialogAbout.setSize(500,250);
        jDialogAbout.setVisible(true);
    }//GEN-LAST:event_jButtonAboutActionPerformed
    
    private void jButtonCancelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelNoActionPerformed
        jDialogCancel.setVisible(false);
    }//GEN-LAST:event_jButtonCancelNoActionPerformed
    
    private void jButtonCancelYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelYesActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jButtonCancelYesActionPerformed
    
    private void jButtonCancelMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelMainActionPerformed
        jDialogCancel.setSize(200, 100);
        jDialogCancel.setVisible(true);
    }//GEN-LAST:event_jButtonCancelMainActionPerformed
    
    private void jButtonSignMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignMainActionPerformed
        jDialogPassword.setSize(400, 120);
        jDialogPassword.setVisible(true);
    }//GEN-LAST:event_jButtonSignMainActionPerformed
    
    private void jButtonSignaturefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignaturefileActionPerformed
        String file = chooseP12File();
        // do nothing if open dialog was cancelled
        if (file == null) {
            return;
        }
        jTextFieldSignaturefile.setText(file);
//        System.out.println(file);
    }//GEN-LAST:event_jButtonSignaturefileActionPerformed
    
    private void jButtonOutputfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOutputfileActionPerformed
        String file = choosePDFFileSave();
        // do nothing if open dialog was cancelled
        if (file == null) {
            return;
        }
        jTextFieldOutputfile.setText(file);
//        System.out.println(file);
    }//GEN-LAST:event_jButtonOutputfileActionPerformed
    
    private void jButtonInputfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInputfileActionPerformed
        String file = choosePDFFile();
        // do nothing if open dialog was cancelled
        if (file == null) {
            return;
        }
        jTextFieldInputfile.setText(file);
//        System.out.println(file);
    }//GEN-LAST:event_jButtonInputfileActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
 //       java.util.Locale Language;
        
        mycommand = new SignCommandLine(args);
        
        if (mycommand.nogui) {
            new DoSignPDF(mycommand.input,
                    mycommand.output,
                    mycommand.signature,
                    mycommand.password);
            System.exit(0);
        } else {
            
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Main().setVisible(true);
                }
            });
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbout;
    private javax.swing.JButton jButtonAboutOk;
    private javax.swing.JButton jButtonCancelMain;
    private javax.swing.JButton jButtonCancelNo;
    private javax.swing.JButton jButtonCancelYes;
    private javax.swing.JButton jButtonFinishBack;
    private javax.swing.JButton jButtonFinishedOK;
    private javax.swing.JButton jButtonInputfile;
    private javax.swing.JButton jButtonOutputfile;
    private javax.swing.JButton jButtonPasswordCancel;
    private javax.swing.JButton jButtonPasswordOK;
    private javax.swing.JButton jButtonSignMain;
    private javax.swing.JButton jButtonSignaturefile;
    private javax.swing.JDialog jDialogAbout;
    private javax.swing.JDialog jDialogCancel;
    private javax.swing.JDialog jDialogFinished;
    private javax.swing.JDialog jDialogPassword;
    private javax.swing.JLabel jLabelAboutCopyright;
    private javax.swing.JLabel jLabelAboutText;
    private javax.swing.JLabel jLabelCancelQuestion;
    private javax.swing.JLabel jLabelFinished;
    private javax.swing.JLabel jLabelInput;
    private javax.swing.JLabel jLabelOutput;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSignature;
    private javax.swing.JPanel jPanelCancel;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JScrollPane jScrollPaneAboutVersion;
    private javax.swing.JTextArea jTextAreaAboutVersion;
    private javax.swing.JTextField jTextFieldInputfile;
    private javax.swing.JTextField jTextFieldOutputfile;
    private javax.swing.JTextField jTextFieldSignaturefile;
    // End of variables declaration//GEN-END:variables
    
    
    /** Opens dialog for user to choose an PDF file to open and read.
     *
     * @return PDF file or null if user cancelled the dialog
     */
    private String choosePDFFile() {
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser(prefs.lastInputFile);
        chooser.setFileFilter(new PDFFilter());
        
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            return chooser.getSelectedFile().getAbsolutePath();
        }
        // cancel was clicked
        return null;
    }
    
    /** Save dialog for user to choose an PDF file to save.
     *
     * @return PDF file or null if user cancelled the dialog
     */
    private String choosePDFFileSave() {
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser(prefs.lastOutputFile);
        chooser.setFileFilter(new PDFFilter());
        
        int returnVal = chooser.showSaveDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            return chooser.getSelectedFile().getAbsolutePath();
        }
        // cancel was clicked
        return null;
    }
    
    /** Opens dialog for user to choose an P12 file to open and read.
     *
     * @return P12 file or null if user cancelled the dialog
     */
    private String chooseP12File() {
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser(prefs.lastP12File);
        chooser.setFileFilter(new P12Filter());
        
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            return chooser.getSelectedFile().getAbsolutePath();
        }
        // cancel was clicked
        return null;
    }
    
    /** Filter which accepts only PDF files */
    private static class PDFFilter extends javax.swing.filechooser.FileFilter {
        public boolean accept(java.io.File f) {
            return f.isDirectory() || f.getName().endsWith(".pdf");
        }
        
        public String getDescription() {
            return java.util.ResourceBundle.getBundle("at/gv/wien/PortableSigner/i18n").getString("PDFDescription");
        }
    }
    
    /** Filter which accepts only P12 files */
    private static class P12Filter extends javax.swing.filechooser.FileFilter {
        public boolean accept(java.io.File f) {
            return f.isDirectory() || f.getName().endsWith(".p12");
        }
        
        public String getDescription() {
            return java.util.ResourceBundle.getBundle("at/gv/wien/PortableSigner/i18n").getString("PKCS12Description");
        }
    }
    
    public static void setResult(String resultText, Boolean errorState) {
        System.err.println(resultText);
        if (result == null) {
            result = resultText;
        }
    }
}
